# The right place for all your configuration values.
data-sources:
    bp:
        url: https://www.energyinst.org/__data/assets/excel_doc/0007/1055545/EI-stats-review-all-data.xlsx
    primary-energy-by-fuel:
        variables:
            coal: Coal Consumption - EJ
            oil: Oil Consumption - EJ
            gas: Gas Consumption - EJ
            hydro: Hydro Consumption - EJ
            nuclear: Nuclear Consumption - EJ
            biofuel: Biofuels consumption - PJ
            solar: Solar Consumption - EJ
            wind: Wind Consumption - EJ
            other renewable: Geo Biomass Other - EJ
        scale: True
    emissions:
        variables:
            emissions_mt: CO2 Emissions from Energy
        scale: False
    primary-energy:
        variables:
            primary_energy_ej: Primary Energy Consumption
        scale: False
    sectoral-emissions:
        name: emissions_mt
        eurostat-dataset-code: env_air_gge
        filter-pars:
            unit: ["MIO_T"]
            geo: ["DE", "ES"]
            src_crf: ["CRF1A2", "CRF1A3", "CRF1A1A", "CRF1A4B"]
            airpol: ["CO2"]
        cat-mapping:
            src_crf:
                CRF1A2: industry
                CRF1A3: transport
                CRF1A1A: power
                CRF1A4B: households
        col-name-mapping:
            src_crf: sector
        additional-index-cols: ["sector"]
    population:
        name: population
        eurostat-dataset-code: DEMO_PJAN
        filter-pars:
            geo: ["DE", "ES"]
            age: ["TOTAL"]
            sex: ["T"]
        cat-mapping: {}
        col-name-mapping: {}
        additional-index-cols: []
    gdp:
        name: gdp_meur
        eurostat-dataset-code: NAMA_10_GDP
        filter-pars:
            unit: ["CLV15_MEUR"]
            geo: ["DE", "ES"]
            na_item: ["B1GQ"]
        cat-mapping: {}
        col-name-mapping: {}
        additional-index-cols: []
parameters:
    first-year: 1998
    periods:
        Germany:
            pre: [1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007]
            global-financial: [2008, 2009]
            post: [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
            covid: [2020, 2021]
        Spain:
            pre: [1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007]
            global-financial: [2008, 2009, 2010, 2011, 2012, 2013]
            post: [2014, 2015, 2016, 2017, 2018, 2019]
            covid: [2020, 2021]
push-directory: ~/Documents/work/Shared
