# The right place for all your configuration values.
data-sources:
    excel:
        path: "data/Germany & Spain Data.xlsx"
        datasets:
            - ["Total", "emissions", 4]
            - ["Total", "energy", 9]
            - ["Total", "gdp", 14]
            - ["Total", "population", 19]
            - ["Industry", "emissions", 3]
            - ["Industry", "energy", 8]
            - ["Industry", "gdp", 13]
            - ["Transport", "emissions", 3]
            - ["Transport", "energy", 8]
            - ["Transport", "gdp", 13]
            - ["Power", "emissions", 3]
            - ["Power", "energy-in", 8]
            - ["Power", "energy-out", 13]
    primary-energy:
        url: https://nyc3.digitaloceanspaces.com/owid-public/data/energy/owid-energy-data.csv
        columns:
            - coal_consumption
            - oil_consumption
            - gas_consumption
            - hydro_consumption
            - nuclear_consumption
            - biofuel_consumption
            - other_renewable_consumption
            - solar_consumption
            - wind_consumption
parameters:
    first-year: 1998
    final-year: 2021
    periods:
        Germany:
            pre: [1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007]
            crisis: [2008, 2009]
            post: [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
            covid: [2020, 2021]
        Spain:
            pre: [1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007]
            crisis: [2008, 2009, 2010, 2011, 2012, 2013]
            post: [2014, 2015, 2016, 2017, 2018, 2019]
            covid: [2020, 2021]
