name: default
channels:
    - conda-forge
dependencies:
    - python=3.10
    - numpy=1.22.3
    - pandas=1.4.1
    - pint=0.18.0
    - xarray=2022.3.0
    - netcdf4=1.5.8
    - matplotlib=3.5.1
    - seaborn=0.11.2
